######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 8 17:24:54 2011
######################################################################

TEMPLATE = app
TARGET = test 
DEPENDPATH += . src
INCLUDEPATH += .
DESTDIR = bin
DEFILES += DEBUG

# Input
SOURCES += src/main.cpp \
		src/testclass.cpp \

HEADERS += include/global.h \
		include/defines.h \
		include/testclass.h  \

message("beta project built")
